import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEdit, faEnvelope, faLanguage } from '@fortawesome/free-solid-svg-icons'
import { faGithub, faGithubSquare, faTelegram, faTwitter } from '@fortawesome/free-brands-svg-icons'
import en from "../public/i18n/en-US";
import zh from "../public/i18n/zh-CN";
import ja from "../public/i18n/ja";
import Link from "next/link";

const Home: NextPage = () => {
  const [data, setData] = useState([{ key: 1, title: "Loading", url: "", summary: "Loading" },])
  useEffect(() => {
    let pageArr = new Array();
    const apiUrl = 'https://blog.picoaoi.com/wp-json/wp/v2/posts';
    fetch(apiUrl, {
      mode: "cors",

    })
      .then((response: any) => {
        response.json()
          .then((response: any) => {
            for (let i = 0; i < 5; i++) {
              pageArr.push({
                key: i,
                title: response[i].title.rendered,
                url: response[i].guid.rendered,
                summary: response[i].excerpt.rendered,
              });
            }
            setData(pageArr)
          })

      })
      .catch((error: any) => {
        console.log(error)
      })
  }, [])
  const [Value, setValue] = useState(0);
  const toLocation = (location: string) => {
    const dom = document.getElementById(location);
    if (dom) {
      dom.scrollIntoView({ block: "start", behavior: "smooth" });
    }
  };
  const [clientHeight, setClientHeight] = useState(0);
  const [scrollHeight, setScrollHeight] = useState(0);

  useEffect(() => {
    setClientHeight(document.documentElement.clientHeight);
    setScrollHeight(document.documentElement.scrollHeight);
    //listen
    window.addEventListener("scroll", handleScoll);
  });
  const handleScoll = () => {
    setValue(window.scrollY);
  };
  let progressMax = scrollHeight - clientHeight;

  const { locale } = useRouter();
  let t;
  if (locale === "zh-CN" || locale === "zh") t = zh;
  else if (locale === "ja") t = ja;
  else t = en;
  return (
    <>
      <div className="container">
        <Head>
          <title>PicoAoi(@robert1chi)</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="main">
          <div className="artboard phone" id="pro">
            <progress
              className="progress dark:progress-primary"
              value={Value}
              max={progressMax}
              id="top"
            ></progress>
          </div>
          <div className="firstPage">
            <div className="absolute top-6 right-6 h-12 w-30 dropdown dropdown-end" id="changeLang">
              <FontAwesomeIcon className="btn btn-ghost left-0" tabIndex={0} icon={faLanguage} />
              <ul tabIndex={0} className="p-2 shadow menu dropdown-content bg-base-200 rounded-box w-52 ">
                <li>
                  <Link href="/" locale="en-US" passHref>English</Link>
                </li>
                <li>
                  <Link href="/zh-CN" locale="zh-CN" passHref>中文</Link>
                </li>
                <li>
                  <Link href="/ja" locale="ja" passHref>日本語</Link>
                </li>
              </ul>
            </div>
            <div id="title">
              <h1 className="title">
                <p className="font-serif text-2xl">
                  {t.hi}
                  <br />
                  <div className="mockup-code font-mono mt-4 mb-4 float-left text-xl">
                    <pre data-prefix="$">
                      <code className="mr-6">PicoAoi<a id="bli">&#8197;</a></code>
                    </pre>
                  </div>
                  <br />
                  {t.glad}
                </p>
              </h1>
            </div>
            <div id="social" className="grid grid-cols-2 gap-4 w-30 font-semibold">
              <div id="blog" className="w-15 h-5 flex text-sky-500 dark:text-violet-400">
                <FontAwesomeIcon className="w-5 h-5 flex-none mr-2" icon={faEdit} />
                <p className="h-5 flex-initial flex justify-center items-center"><a id="blogLine" href="https://blog.picoaoi.com">Blog</a></p>
              </div>
              <div id="github" className="w-15 h-5 flex text-sky-500 dark:text-violet-400">
                <FontAwesomeIcon className="w-5 h-5 flex-none mr-2" icon={faGithub} />
                <p className="h-5 flex-initial flex justify-center items-center"><a id="githubLine" href="https://github.com/robert1chi">GitHub</a></p>
              </div>
            </div>
            <div
              className="contain"
              onClick={() => {
                toLocation("secondPage");
              }}
            >
              <div className="chevron"></div>
              <div className="chevron"></div>
              <div className="chevron"></div>
            </div>
          </div>
          <div id="secondPage">
            <div className="flex" id="box">
              <div className="card shadow-2xl lg:card-side dark:bg-base-200" id="right">
                <div className="avatar">
                  <div className="m-0 rounded-full w-24 h-24">
                    <img src="https://avatars.githubusercontent.com/u/40431036?s=400&u=f7232735cb72d33aeaccad41be051963b3a39ece&v=4" />
                  </div>
                </div>
                <div className="card-body col-span-2">
                  <div id="right">
                    <h2 className="text-xl card-title">{t.aboutMe}</h2>
                    <p>
                      zh-CN · en-US · ja-JP
                      <br />
                      {t.jobs}
                      <br />
                      {t.likes}
                    </p>
                    <p className="mt-1">
                      {t.contriF} <a className="text-blue-500 dark:text-violet-400" id="sakura" href="https://github.com/mirai-mamori/Sakurairo">Sakurairo</a>{t.contriL}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="thirdPage">
            <div className="card shadow-lg dark:bg-base-200" id="card3">
              <div className="card-body">
                <h2 className="card-title">
                  {t.latest}
                </h2>
                <div id="contact" className=" font-mono">
                  <ul>
                    {
                      [...data].map((item: any) => {
                        return (
                          <li key={item.key}>
                            <a href={item.url}>
                              <div id="title">
                                {item.title}
                                <br />
                                <div id="summary" className="text-xs flex" dangerouslySetInnerHTML={{ __html: item.summary }} />
                              </div>
                            </a>
                          </li>
                        )
                      })
                    }
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div id="forthPage">
            <div className="card shadow-lg dark:bg-base-200" id="card3">
              <div className="card-body">
                <h2 className="card-title">{t.contact}</h2>
                <div id="contact" className="ml-20 mr-20 font-mono">
                  <div id="github" className="mt-5 h-5 flex text-zinc-500 dark:text-zinc-200">
                    <FontAwesomeIcon className="w-5 h-5 flex-none mr-2" icon={faGithub} />
                    <p className="h-5 flex-initial flex justify-center items-center">
                      <a href="https://github.com/robert1chi">GITHUB</a>
                    </p>
                  </div>
                  <div id="telegram" className="mt-5 h-5 flex text-zinc-500 dark:text-zinc-200">
                    <FontAwesomeIcon className="w-5 h-5 flex-none mr-2" icon={faTelegram} />
                    <p className="h-5 flex-initial flex justify-center items-center">
                      <a href="https://t.me/aoione_bot">TELEGRAM</a>
                    </p>
                  </div>
                  <div id="twitter" className="mt-5 h-5 flex text-zinc-500 dark:text-zinc-200">
                    <FontAwesomeIcon className="w-5 h-5 flex-none mr-2" icon={faTwitter} />
                    <p className="h-5 flex-initial flex justify-center items-center">
                      <a href="https://twitter.com/robert1chi">TWITTER</a>
                    </p>
                  </div>
                  <div id="email" className="mt-5 h-5 flex text-zinc-500 dark:text-zinc-200">
                    <FontAwesomeIcon className="w-5 h-5 flex-none mr-2" icon={faEnvelope} />
                    <p className="h-5 flex-initial flex justify-center items-center">
                      <a href="#my-modal">EMAIL</a>
                    </p>
                  </div>
                  <div id="my-modal" className="modal">
                    <div className="modal-box">
                      <p>contactus#aoione.xyz(change the # to @)</p>
                      <div className="modal-action">
                        <a onClick={() => {
                          window.history.back();
                        }} className="btn">Close</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
      <footer className="px-10 py-4 border-t footer bg-base-200 text-base-content border-base-300">
        <div className="h-[24px] items-center grid-flow-col">
          <p>© {new Date().getFullYear()} PicoAoi. {t.rights}</p>
        </div>
        <div className="md:place-self-center md:justify-self-end">
          <div id="footerReact">
            <a className="flex flex-row items-center" href="https://pages.github.com/">
              <p>{t.powered}</p>
              <FontAwesomeIcon className="w-[24px] h-[24px] flex-none ml-2" icon={faGithubSquare} />
            </a>
          </div>
        </div>
      </footer>
    </>
  );
};

export default Home;
